-- 1. Create 'issues' table if not exists
CREATE TABLE IF NOT EXISTS public.issues (
    "issueId" TEXT PRIMARY KEY,
    "project" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "discipline" TEXT,
    "priority" TEXT,
    "severity" TEXT,
    "status" TEXT NOT NULL,
    "openDate" TEXT,
    "dueDate" TEXT,
    "closedDate" TEXT,
    "responsible" TEXT,
    "location" TEXT,
    "description" TEXT,
    "workItemType" TEXT DEFAULT 'Issue',
    "createdAt" TIMESTAMPTZ DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and allow public read/write
ALTER TABLE public.issues ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access" ON public.issues;
CREATE POLICY "Allow public access" ON public.issues 
    FOR ALL TO public 
    USING (true) 
    WITH CHECK (true);

-- 2. Create 'upload_history' table if not exists
CREATE TABLE IF NOT EXISTS public.upload_history (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fileName" TEXT NOT NULL,
    "uploadDate" TIMESTAMPTZ DEFAULT NOW(),
    "totalRecords" INT NOT NULL,
    "newRecords" INT NOT NULL,
    "updatedRecords" INT NOT NULL,
    "processingTimeMs" INT NOT NULL,
    "status" TEXT NOT NULL,
    "errors" TEXT[]
);

-- Enable RLS and allow public read/write
ALTER TABLE public.upload_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access" ON public.upload_history;
CREATE POLICY "Allow public access" ON public.upload_history 
    FOR ALL TO public 
    USING (true) 
    WITH CHECK (true);

-- 3. Create 'dashboard_cache' table if not exists
CREATE TABLE IF NOT EXISTS public.dashboard_cache (
    "key" TEXT PRIMARY KEY,
    "data" JSONB NOT NULL,
    "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and allow public read/write
ALTER TABLE public.dashboard_cache ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public access" ON public.dashboard_cache;
CREATE POLICY "Allow public access" ON public.dashboard_cache 
    FOR ALL TO public 
    USING (true) 
    WITH CHECK (true);

-- Force Supabase's PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';
